server:
  port: 8084

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/billingdb?useSSL=false&allowPublicKeyRetrieval=true"
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
